trainingInput:
  pythonVersion: "3.5"
  scaleTier: BASIC
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 80
    maxParallelTrials: 3
    hyperparameterMetricTag: best_metric_sum
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameterName: coe
      type: DISCRETE
      discreteValues:
      - 2
      - 8
      - 16
      - 32
      - 60
      - 80
      - 100
    - parameterName: blocks
      type: INTEGER
      minValue: 1
      maxValue: 2
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: activation
      type: CATEGORICAL
      categoricalValues:
      - relu
      - sigmoid
      - tanh
      - leakyrelu
      - poly
    - parameterName: order1
      type: INTEGER
      minValue: 2
      maxValue: 4
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: order2
      type: INTEGER
      minValue: 2
      maxValue: 4
      scaleType: UNIT_LINEAR_SCALE