trainingInput: 
  pythonVersion: "3.5"
  scaleTier: BASIC
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 50 
    maxParallelTrials: 2
    hyperparameterMetricTag: best_metric_sum
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: layer_num
      type: INTEGER
      minValue: 2
      maxValue: 8
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameterName: coe
      type: DISCRETE
      discreteValues:
      - 8
      - 16
      - 32
      - 60
      - 80
    - parameterName: activation
      type: CATEGORICAL
      categoricalValues:
      - relu
      - sigmoid
      - tanh
      - leakyrelu
