trainingInput:
  pythonVersion: "3.5"
  scaleTier: CUSTOM
  masterType: standard
  workerType: standard
  parameterServerType: standard
  workerCount: 5
  parameterServerCount: 5
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 50
    maxParallelTrials: 5
    hyperparameterMetricTag: best_metric_sum
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameterName: coe
      type: DISCRETE
      discreteValues:
      - 2
      - 8
      - 16
      - 32
      - 60
      - 80
      - 100
    - parameterName: activation
      type: CATEGORICAL
      categoricalValues:
      - relu
      - sigmoid
      - tanh
      - leakyrelu